export const STATUSES = {
  NOT_STARTED: "Not Started",
  IN_PROGRESS: "In Progress",
  COMPLETED: "Completed",
};

export const regularTasks = "Regular Tasks";

export const taskCategories = {
  [regularTasks]: [
    "Brushing teeth",
    "Washing face",
    "Showering",
    "Getting dressed",
    "Making the bed",
    "Preparing and having breakfast",
    "Preparing and packing lunch",
    "Reviewing schedule and tasks for the day",
    "Taking medication or supplements",
    "Active listening",
    "Effective communication",
    "Problem-solving",
    "Decision-making",
    "Empathy",
    "Open-mindedness",
    "Respectfulness",
    "Responsibility",
    "Self-awareness",
    "Self-control",
    "Self-esteem",
    "Perseverance",
  ],
  "Sensory Activities": [
    "finger painting",
    "sensory bin",
    "water play",
    "Bubble wrap popping",
    "Kinetic sand",
    "Scented playdough",
    "Sensory balls or fidget toys",
    "Tactile sensory boards",
    "Sensory bottles filled with glitter or other objects",
    "Sensory walks in nature",
    "Sensory storytelling",
    "Sensory art projects",
    "Sensory rooms or spaces",
    "Weighted blankets or vests",
    "Body socks or tunnels",
    "Trampolines or jumping exercises",
    "Swinging or rocking",
    "Playing with textured fabrics or materials",
    "Tactile puzzles or games",
    "Bubble baths or water play with toys",
    "Playing with slime or oobleck",
    "Sensory integration games like bean bag toss or ball catching",
  ],
  "Personal expression and reflection": [
    "Sensory-friendly cooking or baking",
    "Foam play or shaving cream art",
    "Sensory-friendly gardening or planting",
    "Listening to calming music or sounds",
    "Exploring with different scents and aromas",
    "Sensory-friendly science experiments",
    "Creative writing classes",
    "Role-playing exercises",
    "Improvisation exercises",
    "Personal storytelling",
    "Writing a memoir or personal essay",
    "Participating in a book club or discussion group",
    "Taking a personal development course or workshop",
    "Vision boarding",
    "Dream analysis",
    "Mind mapping",
    "Drawing a self-portrait",
    "Writing a letter to oneself",
    "Creating a personal mission statement",
    "Goal setting",
    "Reflective writing exercises",
    "Analyzing and interpreting personal symbols",
    "Practicing mindfulness",
    "Participating in a spiritual retreat",
    "Chanting or affirmations",
    "Practicing gratitude",
    "Volunteering",
    "Participating in a support group",
    "Building a personal altar",
    "Designing a personal flag or banner",
    "Making a gratitude jar or journal",
    "Creating art",
    "Making music",
    "Dance therapy",
  ],
  "Music Therapy": ["Singing", "Playing instrument", "Listening to music"],
  "Outdoor Activities": [
    "Playing in the park",
    "Going for a walk",
    "Riding a bike",
    "Hiking",
    "Horseback riding",
    "Gardening",
  ],
  "Social Skills Groups": [
    "Team building",
    "Board games that encourage cooperation",
    "Role-playing",
    "Cooperative games",
    "Team sports",
  ],
  "Art Therapy": [
    "Drawing",
    "Painting",
    "Sculpting",
    "Martial arts classes",
    "Drawing or coloring mandalas",
    "Painting with watercolors or acrylics",
    "Creating collages using magazine cutouts or other materials",
    "Making sculptures or 3D art with clay or other materials",
    "Journaling or writing poetry",
    "Creating a vision board with images",
    "Designing and decorating a dreamcatcher",
  ],
  "Physical Activities": [
    "Swimming",
    "Dancing",
    "Yoga",
    "Gardening",
    "Running or jogging",
    "Walking",
    "Skiing",
    "Soccer",
    "Rock climbing",
    "Rafting",
    "Pilates",
    "Tennis",
    "Team sports like football, rugby, or baseball",
    "Roller skating or rollerblading",
    "Basketball",
  ],
  Relaxation: [
    "Progressive muscle relaxation",
    "Body scan meditation",
    "Mindfulness meditation",
    "Deep breathing exercises",
    "Visualization",
    "Listening to soothing music",
    "Taking a warm bath or shower",
    "Spending time in nature",
    "Mindful walking",
    "Reading a book",
    "Watching a movie or TV show",
    "Journaling",
    "Coloring books for adults",
    "Knitting or crocheting",
    "Playing with a pet",
    "Stretching",
    "Taking a nap",
    "Spending time in a sauna or steam room",
    "Having a cup of herbal tea",
    "Doing a puzzle or Sudoku",
    "Getting a manicure or pedicure",
    "Acupuncture",
    "Reiki",
    "Reflexology",
    "Float therapy",
  ],
  "Therapy and communication": [
    "Talk therapy",
    "Cognitive Behavioral Therapy (CBT)",
    "Animal-assisted therapy",
  ],
  "Creative Expression": [
    "Learning and practicing money management skills",
    "Learning and practicing self-advocacy skills",
    "Practicing personal safety skills",
  ],
  "Independent Living Skills": [
    "Learning and practicing money management skills",
    "Learning and practicing self-advocacy skills",
    "Practicing personal safety skills",
  ],
  "Language Skills": [
    "Reading and storytelling",
    "Learning and practicing occupational skills through volunteer or work programs",
    "Word games (e.g. Scrabble, Boggle, Hangman)",
    "Learning new words each week",
    "Picture books",
    "Role-playing",
    "Volunteering for community activities that involve communication skills",
    "Attending speech therapy sessions",
    "Writing stories, letters, or emails",
    "Learning new languages",
    "Conversation practice",
  ],
  "Support groups activities": [
    "Support groups",
    "Group discussions",
    "Role-playing",
    "Creative expression",
    "Mindfulness exercises",
    "Guest speakers",
    "Goal setting",
    "Social activities",
    "Celebrations",
  ],
};
